### ISSUE TITLE
Together page

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#106]
Add a /together landing page which explains how other businesses and organisations can help support the cause...

Styling can follow the styles we've developed for our other internal pages.

Website copy is here > https://docs.google.com/document/d/1qPjhU3gDibR6v2VpRwOFxp2k0As6eayjq_VDpSfv0QE/edit?usp=sharing

**Comment by globalmatt** [comment]
@kelvinlockwood Is this just the black text on page 2 (LANDING PAGE) or also the blue text on page 3?

**Comment by kelvinlockwood** [comment]
@globalmatt ignore the blue text

**Comment by dickyjiang** [comment]
@globalmatt what's the status on this? 
also where's this page accessed from @kelvinlockwood

**Comment by dickyjiang** [comment]
Done
