### ISSUE TITLE
Charity Excellence Framework inclusion

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#107]
We need to add the Charity Excellence Framework logo to our About page > https://www.charityexcellence.co.uk/

I suggest we use the following sentence...

Proudly listed on the Charity Excellence COVID19 funder database  [logo]

**Comment by kelvinlockwood** [comment]
It can be positioned a line below this paragraph... <img width="660" alt="Screen Shot 2020-04-19 at 15 57 22" src="https://user-images.githubusercontent.com/11790973/79691289-8ba70a80-8256-11ea-8018-fa5e95855af0.png">

**Comment by dickyjiang** [comment]
Done added logo
