### ISSUE TITLE
Book genres

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#109]
Arts & Photography
Biographies & Memoirs
Business & Money
Children's
Cookbooks, Food & Drink
Crafts, Hobbies & Home
Health, Fitness & Diet
History
Humour & Entertainment
Mystery, Thriller & Suspense
Poetry & Short Stories
Politics & Social Sciences
Romance
Science & Math
Science Fiction & Fantasy
Self-Help & Spirituality
Sports
Technology
Travel

**Comment by kelvinlockwood** [comment]
Arts & Photography
Biography & Memoir
Business & Money
Children's
Cooking, Food & Drink
Health, Fitness & Diet
History
Hobbies & Crafts
Homes
Humour & Entertainment
Mystery & Suspense
Poetry & Short Stories
Politics & Social Sciences
Romance
Science & Engineering
Sci-Fi & Fantasy
Self Development
Spirituality
Sports
Technology
Travel

**Comment by rvpanchal10** [comment]
@kelvinlockwood I have updated book genres in `planList.js`

Please check and let me know if any.

Thanks,
Ravi Panchal
