### ISSUE TITLE
DVD genres

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#110]
Action
Adventure
Animation
Comedy
Crime
Documentary
Drama
Family
Fantasy
History
Horror
Music
Mystery
Romance
Science Fiction
Thriller
War
Western

**Comment by rvpanchal10** [comment]
@kelvinlockwood I have also updated same on `planList.js`

Please check & verify it.

Thanks,
Ravi Panchal
