### ISSUE TITLE
Add various misc files

### ISSUE THREAD

**Issue by hmajid2301** [Charity-Shop-Exchange/Charity-Shop-Exchange#138]
Add files to Github to make it easier for contributors such as

- [ ] Pull Request Template
- [ ] Issue Template
- [ ] Contributing Guide
- [ ] Code of conduct

**Comment by kelvinlockwood** [comment]
@hmajid2301 just came along an issue template here > https://github.com/ctrl-alt-del-world/midway/tree/master/.github/ISSUE_TEMPLATE

I'm sure there are many more out there!
