### ISSUE TITLE
Look at using Netlify workflow suggestions

### ISSUE THREAD

**Issue by hmajid2301** [Charity-Shop-Exchange/Charity-Shop-Exchange#139]
Look at changing workflow to improve development by making changes suggested by Netlify themselves. https://www.netlify.com/blog/2020/05/12/see-13-netlify-features-for-the-best-control-of-development-workflow/

**Comment by kelvinlockwood** [comment]
PR preview etc

**Comment by hmajid2301** [comment]
- Created `develop` branch
- Tested PR previews

So PR previews were always turned and able to be used by Netlify. You can view them within any PR for the project.

There is now a new staging environment on Netlify which deploys whatever is on the `develop` branch. So the workflow will now be:

```
feature_branch -> develop -> master
```

Where develop is the staging env: `develop.charityshopexchange.com`
and master is prod env: `charityshopexchange.com`

All feature branches should now branch of `develop` instead of `master`. Only the `develop` branch should be merged directly into `master`. This will make it easier to catch bugs before we deploy to production. Issues found can be fixed and merged into the `develop` branch.
