### ISSUE TITLE
SEO considerations

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#151]
1. We need to make sure that we don't have any old versions of the site being hosted elsewhere.

2. We should "noindex" our develop subdomain.

3. From what I understand all of our regional subdomains should have a canonical tag to help search engine bots identify https://charityshopexchange.com as the page that should be ranking.

https://ahrefs.com/blog/canonical-tags/

4.  Netlify and Gatsby both have plugins for generating sitemaps. Some suggestion here that you can have a sitemap index file that references each subdomain, looks complicated so probably easiest to let Netlify / Gatsby handle this > https://webmasters.stackexchange.com/questions/82687/sitemaps-one-per-subdomain-or-one-for-the-base-domain/82743#82743

Resources:
https://www.sitemaps.org/protocol.html#location
https://search.google.com/structured-data/testing-tool/
https://www.portent.com/serp-preview-tool/

**Comment by kelvinlockwood** [comment]
Updated meta tags for social media...

```
<meta property="og:url" content="https://charityshopexchange.com/">
<meta property="og:type" content="website">
<meta property="og:title" content="Book & DVD subscription service by Charity Shop Exchange">
<meta property="og:description" content="Get a regular selection of new things to read and watch, handpicked by your favourite charity shop.">
<meta property="og:image" content=“USE CURRENT IMAGE URL”>
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content=“Charity Shop Exchange’s subscription service“>
<meta name="twitter:site" content=“@CharityShopEx”>
```

Updated tags for search...

```
<meta name="description" content="Get a regular selection of new things to read and watch, handpicked by your favourite charity shop."/>

<title>Book & DVD subscription service by Charity Shop Exchange</title>
```

**Comment by kelvinlockwood** [comment]
I added the new OG tags and tested it on twitter @engjellselaci 

<img width="1136" alt="Screenshot 2020-06-12 at 09 57 17" src="https://user-images.githubusercontent.com/11790973/84484797-2a6a4900-ac93-11ea-8186-9f640ec2a3ec.png">

**Comment by hmajid2301** [comment]
So PR previews by default are not indexed as per this [article](https://community.netlify.com/t/disabling-x-robots-tag-header-on-hosted-site/8857/2).

For branch deploys i.e. `develop` we need to follow, [this process](https://www.netlify.com/blog/2017/04/07/selective-password-protection/). So my solution is to create a file called `extra/_headers.dev`.

```
/*
  X-robots-tag: noindex
```

and then a `netlify.toml` file like:


```toml
[context.branch-deploy]
  command = "yarn build && cp extra/_headers.dev public/_headers"
```

**Comment by kelvinlockwood** [comment]
Some interesting stuff here > https://css-tricks.com/its-all-in-the-head-managing-the-document-head-of-a-react-powered-site-with-react-helmet/

@hmajid2301 not sure if its directly helpful

**Comment by kelvinlockwood** [comment]
@hmajid2301 with regards to the subdomain strategy am I right in saying that its only the regional homepages that will exist... so for example we won't have a dorset.charityshopexchange.com/about

**Comment by hmajid2301** [comment]
no it's the whole site that is aliased. It's serving the same content just netlify will allow those subdomains we defined i.e. dorset to also access it.

**Comment by kelvinlockwood** [comment]
are there any pros and cons?

Each of the homepages will need this...
`<link rel="canonical" href="https://charityshopexchange.com" />`

and if we need the whole site the internal about pages will need...
`<link rel="canonical" href="https://charityshopexchange.com/about" />`

etc, etc

https://github.com/NickCis/gatsby-plugin-react-helmet-canonical-urls

**Comment by hmajid2301** [comment]
not sure about cons, but can add the canonical stuff.

**Comment by kelvinlockwood** [comment]
Thanks!

Just to be clear, every page including the canonical ones should include the link > https://moz.com/learn/seo/canonicalization

**Comment by kelvinlockwood** [comment]
I've done some more reading on sitemaps and there's no real sense for each subdomain to include one.

So we'll just have one for charityshopexchange.com that includes our internal pages... about, register and faq

We should leave out the terms, customer-terms and privacy pages, to signal to the search engines that these are low interest pages.

**Comment by kelvinlockwood** [comment]
Google also recommends this...

<img width="638" alt="Screenshot 2020-06-18 at 12 54 26" src="https://user-images.githubusercontent.com/11790973/85017267-1b880880-b163-11ea-9500-a40e35f5bf4b.png">

**Comment by kelvinlockwood** [comment]
Gone a bit further down the rabbit hole!

Bing makes use of this tag... <meta name="geo.region" content="GB" />

**Comment by hmajid2301** [comment]
> So PR previews by default are not indexed as per this [article](https://community.netlify.com/t/disabling-x-robots-tag-header-on-hosted-site/8857/2).
> 
> For branch deploys i.e. `develop` we need to follow, [this process](https://www.netlify.com/blog/2017/04/07/selective-password-protection/). So my solution is to create a file called `extra/_headers.dev`.
> 
> ```
> /*
>   X-robots-tag: noindex
> ```
> 
> and then a `netlify.toml` file like:
> 
> ```toml
> [context.branch-deploy]
>   command = "yarn build && cp extra/_headers.dev public/_headers"
> ```

This can be done using gatsby robots plugin instead to simplify the logic.

**Comment by kelvinlockwood** [comment]
@hmajid2301 could you check off the things we've tackled...

- [ ] old versions of site taken down
- [ ] canonical tags on host domain and subdomains
- [ ] geo.region meta tag
- [ ] sitemap to include about, faq and register pages and listed in robots.txt
- [ ] noindex staging site

Is there anything else we need? https://htmlhead.dev/
