### ISSUE TITLE
Web Share API

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#27]
The goal here is to encourage people to share the regional version of the site on Facebook.

https://web.dev/web-share/

The button here is a nice design and might work at the top of the page > https://css-tricks.com/how-to-use-the-web-share-api/

Some discussion on fallbacks in this repo but to be honest we can start with no fallbacks and add them another day > https://github.com/peterpeterparker/web-social-share

**Comment by globalmatt** [comment]
Sounds fun! I'll give it a go.

**Comment by kelvinlockwood** [comment]
This is a screenshot of the Share button that is currently used on Facebook. It makes sense to follow this design because its agnostic - just like the Web Share API functionality.

<img width="100" alt="Screen Shot 2020-03-30 at 23 06 10" src="https://user-images.githubusercontent.com/11790973/77966513-1b523c80-72db-11ea-872a-60a5b4f28760.png">

This is the nearest icon I could find > https://www.flaticon.com/free-icon/share_1946415

**Comment by kelvinlockwood** [comment]
The Share button will be situated in the top right hand corner (where Log in is currently positioned)

So the top nav will look something like this...

#### Subscribe   Log in   <img width="100" alt="Screen Shot 2020-03-30 at 23 06 10" src="https://user-images.githubusercontent.com/11790973/77967305-c31c3a00-72dc-11ea-98b9-280458380551.png">

To keep the Share button on display as the user scrolls we can use sticky positioning > https://webdesign.tutsplus.com/tutorials/sticky-positioning-with-nothing-but-css--cms-24042

**Comment by dickyjiang** [comment]
How do you want it styled ? Just like the current login button?

**Comment by kelvinlockwood** [comment]
No, remove the red button

**Comment by kelvinlockwood** [comment]
Lets remove the edge / outline of the button...

<img width="136" alt="Screen Shot 2020-03-31 at 16 39 35" src="https://user-images.githubusercontent.com/11790973/78045813-4a65be00-736e-11ea-8be9-f8b4f6bd296a.png">

The button should be white, that way it will gently stand out from the background as the user scrolls.

**Comment by globalmatt** [comment]
Share button now implemented.
