### ISSUE TITLE
Create charity registration page/form

### ISSUE THREAD

**Issue by globalmatt** [Charity-Shop-Exchange/Charity-Shop-Exchange#37]
https://charityshopexchange.com/register

**Comment by kelvinlockwood** [comment]
This page is too narrow and long at the moment... we should limit the amount a user has to scroll on a desktop browser.

**Comment by globalmatt** [comment]
@kelvinlockwood @dickyjiang Taking a look at this now

**Comment by globalmatt** [comment]
@kelvinlockwood @dickyjiang Form is now wider, especially on narrower desktop browsers. Better now do you think?

**Comment by kelvinlockwood** [comment]
Yeah looks good to me!
