### ISSUE TITLE
Metropolis font is not displaying

### ISSUE THREAD

**Issue by globalmatt** [Charity-Shop-Exchange/Charity-Shop-Exchange#46]
It's just using the default browser font for headings.

<img width="843" alt="Screen Shot 2020-03-30 at 2 59 58 pm" src="https://user-images.githubusercontent.com/885411/77873964-2daa8700-7297-11ea-8a43-a7a23e50a35e.png">

**Comment by kelvinlockwood** [comment]
when the page loads the font that was causing us an issue loads first, and then Metropolis replaces it

**Comment by globalmatt** [comment]
> when the page loads the font that was causing us an issue loads first, and then Metropolis replaces it

That's called FOUT (or [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)). Unfortunately it happens a lot with newer versions of Chrome and Safari.

I might see if I can work around it using [this](https://www.npmjs.com/package/webfontloader).

**Comment by globalmatt** [comment]
I've made a couple of changes which should mitigate this issue.

@kelvinlockwood @dickyjiang @Prouty89 - can you please confirm that there is no longer any "flash of unstyled text" for you when the page loads? (The Metropolis font in the red headings should appear pretty much straight away, without the system font appearing first.)

**Comment by globalmatt** [comment]
@dickyjiang Also note that part of the fix was to strip back the Metropolis font to just the 700 weight so it loads much more quickly. If you need to use any other weights, please let me know and I'll add them back in.

**Comment by dickyjiang** [comment]
Ok with me this morning @matt

**Comment by globalmatt** [comment]
> Ok with me this morning @matt

Thanks @dickyjiang. 😃 Closing.
