### ISSUE TITLE
Responding to the Coronavirus Crisis section

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#54]
This section was previously titled We're in this together.

Apply updated copy in the google doc.

Layout could be more central to the page.

**Comment by kelvinlockwood** [comment]
Need to copy and paste the text in the google doc as edits have been missed.

**Comment by kelvinlockwood** [comment]
Probably better to depend on system fonts for the body text and use Metropolis for headlines only.

**Comment by dickyjiang** [comment]
Well it is right now .. @kelvin
