### ISSUE TITLE
Slow down box animation?

### ISSUE THREAD

**Issue by globalmatt** [Charity-Shop-Exchange/Charity-Shop-Exchange#56]
@dickyjiang I love the new animated box GIF on the homepage! :)

<img width="226" alt="image" src="https://user-images.githubusercontent.com/885411/77969706-12db1f80-7336-11ea-832f-9d4a7e9337dd.png">

I'm thinking it might be good to put, say, a 2-3 second delay between each "bounce" of the box to make the animation more subtle? Currently the delay is under 1 second and personally I find it a bit too "busy" and distracting. Might just be me though! What do you think?

**Comment by kelvinlockwood** [comment]
Yeah it doesn't work in its current state. I need to discuss with Dicky if and how he wants to iterate on the doorstep design that Drew kicked off - obviously this would be part of that.

**Comment by dickyjiang** [comment]
Yes @matt I just showing possibilty to @kelvin, that we can add in simple animated gif for the home.

**Comment by globalmatt** [comment]
@dickyjiang cool :)
