### ISSUE TITLE
Homepage text issues

### ISSUE THREAD

**Issue by globalmatt** [Charity-Shop-Exchange/Charity-Shop-Exchange#67]
- Increase font size of the subhead at the top of the page
- Prevent subhead text being cut off
- Fix heading capitalisation (sentence case)
- Fix typos and broken links

**Comment by kelvinlockwood** [comment]
@globalmatt @dickyjiang could you update the text so that **We** always begins on the second line in the desktop view...

<img width="516" alt="Screen Shot 2020-04-02 at 15 38 40" src="https://user-images.githubusercontent.com/11790973/78262650-cc81ee00-74f8-11ea-8299-4f292fd8aaa6.png">

**Comment by globalmatt** [comment]
@kelvinlockwood Did you _literally_ mean: "always start a new line on **We**", or did you simply want to have a non-breaking space between "We" and "collect" so that "We" isn't orphaned on the end of the line?

@dickyjiang has implemented the former:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/885411/78335338-2a860280-75d9-11ea-8abb-28bf2235d0b2.png">

... but I was thinking the latter was what you meant?

> @globalmatt @dickyjiang could you update the text so that **We** always begins on the second line in the desktop view...
> 
> <img alt="Screen Shot 2020-04-02 at 15 38 40" width="516" src="https://user-images.githubusercontent.com/11790973/78262650-cc81ee00-74f8-11ea-8299-4f292fd8aaa6.png">

**Comment by dickyjiang** [comment]
I think I already fix this one @matt. Put span from we ... on ward

**Comment by globalmatt** [comment]
> I think I already fix this one @matt. Put span from we ... on ward

Yeah I know, I just think it would be better if it was a simple non-breaking space. But I'm not clear on what Kelvin wanted exactly, hence my question.

**Comment by globalmatt** [comment]
Looks great now @dickyjiang - thanks 😀
