### ISSUE TITLE
Create Launching Soon modal

### ISSUE THREAD

**Issue by globalmatt** [Charity-Shop-Exchange/Charity-Shop-Exchange#75]
When a visitor clicks Continue, pop up a modal for now saying: "We’re launching in a few days, follow us on Twitter for announcements".

**Comment by globalmatt** [comment]
@kelvinlockwood @dickyjiang Please let me know if you want me to change anything with the dialog.

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/885411/78325314-00c1e100-75c3-11ea-8c3f-fd57bb7e0931.png">

**Comment by dickyjiang** [comment]
Make the popup smaller, max 40% of the viewport width (w-2/5 in tailwind)

Make all text smaller heading, body, and especially the twitter link (dont make it bold) 
Center aligned

That's my opinion @matt

**Comment by globalmatt** [comment]
@dickyjiang How's this looking now?

<img width="975" alt="image" src="https://user-images.githubusercontent.com/885411/78334470-91a2b780-75d7-11ea-9b46-57cd2c1fce8b.png">

**Comment by dickyjiang** [comment]
👍👍

**Comment by globalmatt** [comment]
Great, thanks! Closing this then 😀

**Comment by kelvinlockwood** [comment]
@globalmatt I just noticed the Subscribe now link further down the homepage doesn't link to anything...

**Comment by globalmatt** [comment]
@kelvinlockwood You mean "Subscribe here"? It opens the modal because we haven't implemented the integration with Subbly (now Billsby).
