### ISSUE TITLE
Buttons for CTAs on homepage

### ISSUE THREAD

**Issue by globalmatt** [Charity-Shop-Exchange/Charity-Shop-Exchange#88]
I think buttons instead of plain text for "Subscribe here"/"Learn more about our approach"/"Enlist now" would be clearer, as well as being easier to tap on mobile.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/885411/78416077-ed218380-7671-11ea-8774-6f831e70249f.png">
<img width="240" alt="image" src="https://user-images.githubusercontent.com/885411/78416079-f0b50a80-7671-11ea-8bfa-39e6e8208a03.png">
<img width="172" alt="image" src="https://user-images.githubusercontent.com/885411/78416086-fc083600-7671-11ea-9818-f8bb118d343c.png">

**Comment by kelvinlockwood** [comment]
@globalmatt I agree we've gone a bit off track with these. In my opinion the links should come with arrows rather than big buttons... being confronted with lots of big "click me" buttons can be off-putting...

Stripe is a good example > https://stripe.com/

**Comment by kelvinlockwood** [comment]
Another pattern to consider is "becoming buttons on rollover"

Here's an example I've just seen on Buy Me A Coffee...

<img width="329" alt="Screen Shot 2020-04-04 at 10 47 22" src="https://user-images.githubusercontent.com/11790973/78423942-ed198780-7661-11ea-8cd1-628bcb554433.png">

**Comment by globalmatt** [comment]
> Another pattern to consider is "becoming buttons on rollover"
> 
> Here's an example I've just seen on Buy Me A Coffee...
> 
> <img alt="Screen Shot 2020-04-04 at 10 47 22" width="329" src="https://user-images.githubusercontent.com/11790973/78423942-ed198780-7661-11ea-8cd1-628bcb554433.png">

They look nice, but they don't work on mobile of course.

I like the arrow idea - I'll give that a shot 👍

**Comment by globalmatt** [comment]
@kelvinlockwood Added arrows: https://charityshopexchange.com

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/885411/78472074-7bccf800-7779-11ea-8112-42564496813b.png">
