### ISSUE TITLE
Charity Shop Exchange website preview image

### ISSUE THREAD

**Issue by kelvinlockwood** [Charity-Shop-Exchange/Charity-Shop-Exchange#94]
<img width="1021" alt="CharityShopExchange_website" src="https://user-images.githubusercontent.com/11790973/78511026-56e47f00-7791-11ea-9931-62821c0bbb5f.png">

**Comment by globalmatt** [comment]
@kelvinlockwood Is this for Facebook newsfeeds (the `og:image`)?
